laguange: node_js
node_js:
  - '6.5.0'
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm run bower install
script:
  - npm run test
  - npm run gulp
cache:
  - node_modules